name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - <<'PY'
          import nltk
          nltk.download('punkt'); nltk.download('stopwords')
          PY

      - name: Sanity import
        run: python -c "import qhe_forensic_nlp as m; print('import ok, version=', getattr(m,'__version__','?'))"

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1
