name: Build API Docs (pdoc)
on:
  workflow_dispatch:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install doc deps
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Build pdoc HTML into docs/api
        run: python -m pdoc --html --output-dir docs/api src/qhe_forensic_nlp
      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: site-api
          path: docs/api
